### ISSUE TITLE
Can't compile properly EXE for windows 

### ISSUE THREAD

**Issue by nickGaiot** [bri3d/VW_Flash#107]
I'm trying to build VW_flash for Windows to resolve the issue with UNLOCKING in the latest release, but I can't get the 'select interfaces' part to work. It won't show the 'openport' interface like in the official release. It seems strange, like I'm missing some files in between or I'm compiling it incorrectly. 
I installed all the requirements.
the openport dll an drivers.
python setup.py py2exe.
pyinstaller vw_flash_gui.spec.

**Comment by bri3d** [comment]
https://github.com/bri3d/VW_Flash/actions/runs/6066115724
