### ISSUE TITLE
Can´t unlock 

### ISSUE THREAD

**Issue by DAVelasquezC** [bri3d/VW_Flash#111]
Hi,

I think that Im doing it right but maybe Im not.
Thanks you

[flash.log](https://github.com/bri3d/VW_Flash/files/12908133/flash.log)
[flash_details.log](https://github.com/bri3d/VW_Flash/files/12908134/flash_details.log)
[udsoncan.log](https://github.com/bri3d/VW_Flash/files/12908135/udsoncan.log)

<img width="470" alt="Captura de pantalla 2023-10-14 193413" src="https://github.com/bri3d/VW_Flash/assets/147335288/b52453d6-7223-4159-ac02-73f1636f5c91">

<img width="867" alt="Captura de pantalla 2023-10-14 193826" src="https://github.com/bri3d/VW_Flash/assets/147335288/b6fa4ff2-8eba-4ab8-8c4c-57b80a8212b4">

**Comment by bri3d** [comment]
This ECU has the immobilizer locked, so it will not enter a programming session. If it's out of a car, this is to be expected.
