### ISSUE TITLE
VW_Flash wont connect_Simos Tools doesnt work_MachinoA0 on 0.9 

### ISSUE THREAD

**Issue by Mushlet** [bri3d/VW_Flash#117]
Got a brand new Macchino A0 which has been flashed with Switch 0.9 firmware. That goes well.

SimosTools doesnt connect 
VW_Flash doesnt connect and has the following log...

Any ideas what is missing here? All help much appreciated

![Screenshot 2023-12-24 144143](https://github.com/bri3d/VW_Flash/assets/154743037/4f3388d1-db9f-434a-8d89-8005e9cbcdda)

**Comment by bri3d** [comment]
To use 0.9 with VW_Flash, you need to use J2534 rather than the direct connection functionality. The direct connection functionality is scheduled to be removed entirely in the future.

**Comment by Mushlet** [comment]
So select the J2534 option instead?

That gives this...
![Uploading Screenshot 2023-12-24 145223.png…]()

**Comment by Mushlet** [comment]
Doesnt really explain why simos tools also wont connect. 

Is there any data that i can collect that you may want to see to help? I appreciate your time

**Comment by Mushlet** [comment]
Ive no idea how, other than reinstalling the full lot for about the 15th time.... but now it connects on both the simostools app and vw flash.
