### ISSUE TITLE
vw_flash cannot unpack non-iterable nonetype object

### ISSUE THREAD

**Issue by Eddy0697** [bri3d/VW_Flash#119]
I can't convert the FRF to BIN. where is the problem?
vw_flash dashing module not loadet
vw_flash cannot unpack non-iterable nonetype object

**Comment by bri3d** [comment]
Which FRF (filename)? What control module is it for? Can I have a real error log, or even a screenshot?

**Comment by Eddy0697** [comment]
FL_8V0906259J__0003 
Simos 18.1

**Comment by Eddy0697** [comment]
Is there no solution?

**Comment by bri3d** [comment]
I was able to reproduce the issue, looking at it now. I think if you download the previous version of VW_Flash_GUI, it should work.
