### ISSUE TITLE
Simos 18.1

### ISSUE THREAD

**Issue by Wakky22** [bri3d/VW_Flash#128]
![Untitled](https://github.com/bri3d/VW_Flash/assets/40809857/8ef816f2-b860-4595-b1a3-a1c41d9886d9)
[flash.log](https://github.com/bri3d/VW_Flash/files/15370988/flash.log)
[flash_details.log](https://github.com/bri3d/VW_Flash/files/15370989/flash_details.log)
[udsoncan.log](https://github.com/bri3d/VW_Flash/files/15370990/udsoncan.log)
 can anyone help here please thanks

**Comment by aarons3** [comment]
Move the lib/lzss/lzss.exe folder and files from the "_internal" folder to
the same folder that VW_Flash_GUI.exe is in.
