### ISSUE TITLE
Attempting to flash Simos 12 or Extract FRF

### ISSUE THREAD

**Issue by nickGaiot** [bri3d/VW_Flash#34]
Hi, today first I tried to get bins out of my `fl_8v0906259k__0003.frf ` FRF but i get an error that I also got when I tried to flash the FRF to the car, the line that I ran is `sudo python VW_Flash.py --action flash_frf --simos12 --frf frf/FL_8V0906259K__0003.frf `  when trying without the --simos12 flag it works, maybe is only and issue with the simos 12 part .
![Immagine 2022-01-31 223240](https://user-images.githubusercontent.com/45382979/151876580-7bb1511f-693b-42e0-ba2d-1049105417a4.png)
[flash_details.log](https://github.com/bri3d/VW_Flash/files/7974400/flash_details.log)
[flash.log](https://github.com/bri3d/VW_Flash/files/7974401/flash.log)
[udsoncan.log](https://github.com/bri3d/VW_Flash/files/7974402/udsoncan.log)

**Comment by bri3d** [comment]
FL_8V0906259K__0003 is Simos18 software, so it doesn't work with the Simos12 switch since the AES keys are different.

**Comment by nickGaiot** [comment]
Thanks, after I posted this I discovered that is for Simos 18 now I have further questions, but I  wrote you an email because are not exactly an issue .
