### ISSUE TITLE
IM NTERESTED IN THIS, IM SURPRISED THERE'S NOT MORE PROJECS LIKE THIS

### ISSUE THREAD

**Issue by onejay09** [bri3d/VW_Flash#39]
I THINK YOUR WIKI LACKS INFORMATION, CAN YOU UPTATE IT PLEASE...

**Comment by bri3d** [comment]
there's as much information as you could ever want here: https://github.com/bri3d/VW_Flash/blob/master/docs/docs.md

if by "information" you actually mean "step by step instructions," I've got those here: https://github.com/bri3d/VW_Flash/blob/master/docs/windows.md
