### ISSUE TITLE
v0.2.9 broke BLE device scan

### ISSUE THREAD

**Issue by aarons3** [bri3d/VW_Flash#46]
See attachment.  BLE scan breaks the "device select" functionality.  With BT disabled on the machine, the device select functionality works as intended (with no BLE scan of course).  See pic/attachment:

https://user-images.githubusercontent.com/94764002/167018616-0c19b805-dbed-4665-ad1f-d903f7bf18c4.png

**Comment by bri3d** [comment]
It looks like this is a Windows specific issue, I will look more into it shortly.

**Comment by bri3d** [comment]
Fixed in d6b6b38e192199f11399c2e0f039ec44ee1f438d . Will cut another release soon.
