### ISSUE TITLE
Error installing wxpython

### ISSUE THREAD

**Issue by Kayroldizlan** [bri3d/VW_Flash#48]
``I facing this issue and whenever i reinstall.same thing happen

 

> Building` wheels for collected packages: wxpython
>   Running setup.py bdist_wheel for wxpython ... error
>   Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-44632auo/wxpython/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-cpmdrh0i --python-tag cp37:
>   running bdist_wheel
>   running build
>   WARNING: Building this way assumes that all generated files have been
>   generated already.  If that is not the case then use build.py directly
>   to generate the source and perform the build stage.  You can use
>   --skip-build with the bdist_* or install commands to avoid this
>   message and the wxWidgets and Phoenix build steps in the  future

**Comment by bri3d** [comment]
Are you using Python 3.10? You need to use Python 3.9 for now. wxpython _still_ have not pushed an official release which is compatible with 3.10.
