### ISSUE TITLE
Quick dummy check (Not an issue)

### ISSUE THREAD

**Issue by loskani** [bri3d/VW_Flash#62]
Hello, VW_FLASH team

I am owning USDM GOLF 1.8 TSI (AT) with Part number 8V0906264D 0002.
As I know FL_8V0906264K__0003.frf never was a direct factory/recall update of 8V0906264D.

Revisions chronology was like this: 
8V0906264D 0001 --> 0004
and after that changed the part number to  5GM906264 0001.

I truly believe that it is safe to flash 8V0906264K 0003 but maybe some features are not fully compatible?

Sorry for the dummy question.

![image](https://user-images.githubusercontent.com/110221720/181709774-a5534252-2502-4ba6-926c-9ee9e245c33e.png)
![image](https://user-images.githubusercontent.com/110221720/181709922-89f443f2-f581-427d-b9b3-491f555e4ca3.png)

**Comment by aarons3** [comment]
I know a few guys have done this with no apparent issues, and it's listed as "compatible" in the ODX file.  Really it doesn't matter as long as you have a matching definition file-- the choice is yours.

![image](https://user-images.githubusercontent.com/94764002/181767392-dfc4cbc7-cc16-453e-9b70-c281e8623b16.png)
