### ISSUE TITLE
stmin_tx slider

### ISSUE THREAD

**Issue by loskani** [bri3d/VW_Flash#74]
![image](https://user-images.githubusercontent.com/110221720/193558679-1190e8cf-9c35-4cc0-bb81-9d285b8efbd9.png)

if you try adjust STMIN_TX it goes to 1000 (max value) 

![image](https://user-images.githubusercontent.com/110221720/193558942-3b5dc6d1-24da-4f55-aa3a-983dd329689e.png)

you can't go back to 35000 (default value) because max value you can select is 1000.

**Comment by bri3d** [comment]
The whole thing should just be divided by 1000. Also the widget is scaled weird on your machine, I'll make the dialog bigger I guess so the buttons aren't smashed.

Will fix in a new release shortly
