### ISSUE TITLE
Manual for DQ250 write?

### ISSUE THREAD

**Issue by ButcherDSM** [bri3d/VW_Flash#75]
Hello

manual for DQ250, like this https://github.com/bri3d/VW_Flash/blob/master/docs/windows.md is exist?

thanks

**Comment by bri3d** [comment]
Convert FRF to BIN
Edit BIN
Full Flash Unlocked BIN

Done

There is no unlocking or special process for DQ250.

**Comment by ButcherDSM** [comment]
thank you very much
