### ISSUE TITLE
Stuck at "SETUP - Upgrading to programming session"

### ISSUE THREAD

**Issue by JeremyHinderfeld** [bri3d/VW_Flash#90]
Hey ! Everything works fine.. ID successful, but its stuck at Upgrading to programming session. Any Idea, whats going on ?

[flash.log](https://github.com/bri3d/VW_Flash/files/11240937/flash.log)
[flash_details.log](https://github.com/bri3d/VW_Flash/files/11240939/flash_details.log)
[udsoncan.log](https://github.com/bri3d/VW_Flash/files/11240940/udsoncan.log)

**Comment by Antakid12** [comment]
How do you solve it??
